name: cody
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.11.6
- numpy=2.2.6
- Pillow=11.2.1
- python-dotenv=1.1.0
- Requests=2.32.3
- pip
- pip:
  - Flask==3.1.1
  - torch==2.7.0
  - torchvision==0.22.0
  - ultralytics==8.3.146
